/**
 * Dummy data for SkillVersity platform
 * Used when backend doesn't return data
 * Updated: December 2025
 */

export const skillversityCourses = [
  {
    id: "sv-001",
    title: "Full-Stack Web Development Bootcamp",
    slug: "full-stack-web-development-bootcamp",
    description: "Master modern web development with React, Node.js, and PostgreSQL. Build real-world projects and deploy to production.",
    course_type: "pre_made" as const,
    instructor: {
      id: "skillversity",
      first_name: "SkillVersity",
      last_name: "Team",
      instructor_type: "platform",
      is_verified: true,
    },
    price: "25000",
    currency: "PKR",
    enrolled_count: 1250,
    rating_average: "4.8",
    rating_count: 342,
    status: "published",
    created_at: "2025-09-15",
    difficulty: "Beginner to Advanced",
    duration_weeks: 16,
    technologies: ["React", "Node.js", "PostgreSQL", "TypeScript", "Docker"],
  },
  {
    id: "sv-002",
    title: "Python for Data Science & AI",
    slug: "python-data-science-ai",
    description: "Learn Python programming, data analysis with Pandas, machine learning with scikit-learn, and deep learning with TensorFlow.",
    course_type: "pre_made" as const,
    instructor: {
      id: "skillversity",
      first_name: "SkillVersity",
      last_name: "Team",
      instructor_type: "platform",
      is_verified: true,
    },
    price: "20000",
    currency: "PKR",
    enrolled_count: 890,
    rating_average: "4.7",
    rating_count: 215,
    status: "published",
    created_at: "2025-10-01",
    difficulty: "Beginner",
    duration_weeks: 12,
    technologies: ["Python", "Pandas", "NumPy", "scikit-learn", "TensorFlow"],
  },
  {
    id: "sv-003",
    title: "Mobile App Development with React Native",
    slug: "mobile-app-react-native",
    description: "Build cross-platform mobile apps for iOS and Android using React Native. Includes app store deployment.",
    course_type: "pre_made" as const,
    instructor: {
      id: "skillversity",
      first_name: "SkillVersity",
      last_name: "Team",
      instructor_type: "platform",
      is_verified: true,
    },
    price: "22000",
    currency: "PKR",
    enrolled_count: 567,
    rating_average: "4.6",
    rating_count: 128,
    status: "published",
    created_at: "2025-10-15",
    difficulty: "Intermediate",
    duration_weeks: 10,
    technologies: ["React Native", "JavaScript", "Expo", "Firebase"],
  },
  {
    id: "sv-004",
    title: "Cloud Computing with AWS",
    slug: "cloud-computing-aws",
    description: "Master AWS services including EC2, S3, Lambda, and more. Prepare for AWS Solutions Architect certification.",
    course_type: "live" as const,
    instructor: {
      id: "skillversity",
      first_name: "SkillVersity",
      last_name: "Team",
      instructor_type: "platform",
      is_verified: true,
    },
    price: "30000",
    currency: "PKR",
    enrolled_count: 423,
    rating_average: "4.9",
    rating_count: 98,
    status: "published",
    created_at: "2025-11-01",
    difficulty: "Intermediate",
    duration_weeks: 8,
    technologies: ["AWS", "EC2", "S3", "Lambda", "CloudFormation"],
  },
  {
    id: "sv-005",
    title: "UI/UX Design Fundamentals",
    slug: "ui-ux-design-fundamentals",
    description: "Learn user interface and user experience design principles. Master Figma and create stunning designs.",
    course_type: "pre_made" as const,
    instructor: {
      id: "skillversity",
      first_name: "SkillVersity",
      last_name: "Team",
      instructor_type: "platform",
      is_verified: true,
    },
    price: "15000",
    currency: "PKR",
    enrolled_count: 756,
    rating_average: "4.5",
    rating_count: 189,
    status: "published",
    created_at: "2025-11-15",
    difficulty: "Beginner",
    duration_weeks: 6,
    technologies: ["Figma", "Adobe XD", "Prototyping", "User Research"],
  },
  {
    id: "sv-006",
    title: "DevOps & CI/CD Pipeline Mastery",
    slug: "devops-cicd-mastery",
    description: "Learn DevOps practices, Docker, Kubernetes, and build automated CI/CD pipelines with GitHub Actions.",
    course_type: "live" as const,
    instructor: {
      id: "skillversity",
      first_name: "SkillVersity",
      last_name: "Team",
      instructor_type: "platform",
      is_verified: true,
    },
    price: "28000",
    currency: "PKR",
    enrolled_count: 312,
    rating_average: "4.8",
    rating_count: 76,
    status: "published",
    created_at: "2025-12-01",
    difficulty: "Advanced",
    duration_weeks: 10,
    technologies: ["Docker", "Kubernetes", "GitHub Actions", "Jenkins", "Terraform"],
  },
];

export const dummyArticles = [
  // Article from SkillVersity Platform
  {
    id: 1,
    title: "Welcome to SkillVersity: Your Path to Professional Growth",
    slug: "welcome-skillversity-professional-growth",
    excerpt: "Discover how SkillVersity bridges the skills gap in Pakistan through verified learning and professional networking.",
    content: "# Welcome to SkillVersity...",
    author: {
      id: "skillversity",
      first_name: "SkillVersity",
      last_name: "Team",
      author_type: "platform",
    },
    tags: ["SkillVersity", "Career", "Learning"],
    read_time: 5,
    views_count: 3500,
    likes_count: 245,
    published_at: "2025-12-08T10:00:00Z",
  },
  // Article from Verified Tutor (Professional Profile)
  {
    id: 2,
    title: "Getting Started with React in 2025",
    slug: "getting-started-react-2025",
    excerpt: "A comprehensive guide to starting your React journey with the latest best practices and tools.",
    content: "# Getting Started with React...",
    author: {
      id: "user-1",
      first_name: "Ahmed",
      last_name: "Hassan",
      author_type: "tutor",
      is_verified: true,
    },
    tags: ["React", "JavaScript", "Frontend"],
    read_time: 8,
    views_count: 1250,
    likes_count: 89,
    published_at: "2025-12-05T10:00:00Z",
  },
  // Article from Learner (Professional Profile)
  {
    id: 3,
    title: "My Journey: From Beginner to Data Scientist",
    slug: "journey-beginner-data-scientist",
    excerpt: "How I transitioned from a non-tech background to landing my dream data science role in 18 months.",
    content: "# My Journey...",
    author: {
      id: "user-2",
      first_name: "Sara",
      last_name: "Khan",
      author_type: "learner",
      is_verified: false,
    },
    tags: ["Career", "Data Science", "Learning"],
    read_time: 10,
    views_count: 2100,
    likes_count: 156,
    published_at: "2025-12-03T10:00:00Z",
  },
  // Article from Company
  {
    id: 4,
    title: "What We Look for When Hiring Junior Developers",
    slug: "hiring-junior-developers-tips",
    excerpt: "Insights from TechCorp Pakistan's hiring team on what makes candidates stand out.",
    content: "# What We Look for...",
    author: {
      id: "company-1",
      first_name: "TechCorp",
      last_name: "Pakistan",
      author_type: "company",
      is_verified: true,
    },
    tags: ["Hiring", "Career Tips", "Jobs"],
    read_time: 7,
    views_count: 1890,
    likes_count: 134,
    published_at: "2025-12-01T10:00:00Z",
  },
  // Another Tutor Article
  {
    id: 5,
    title: "Design Systems: A Complete Guide for 2025",
    slug: "design-systems-complete-guide-2025",
    excerpt: "Learn how to build and maintain scalable design systems that your team will actually use.",
    content: "# Design Systems...",
    author: {
      id: "user-3",
      first_name: "Ali",
      last_name: "Raza",
      author_type: "tutor",
      is_verified: true,
    },
    tags: ["UI/UX", "Design Systems", "Figma"],
    read_time: 15,
    views_count: 890,
    likes_count: 67,
    published_at: "2025-11-28T10:00:00Z",
  },
  // Platform Educational Article
  {
    id: 6,
    title: "How Skill Verification Works on SkillVersity",
    slug: "skill-verification-explained",
    excerpt: "Understanding our tutor-verified skill system and how it helps you stand out to employers.",
    content: "# How Skill Verification Works...",
    author: {
      id: "skillversity",
      first_name: "SkillVersity",
      last_name: "Team",
      author_type: "platform",
    },
    tags: ["SkillVersity", "Skills", "Verification"],
    read_time: 6,
    views_count: 1560,
    likes_count: 98,
    published_at: "2025-11-25T10:00:00Z",
  },
];

// Author types for articles
export type ArticleAuthorType = "platform" | "tutor" | "learner" | "company";

export const dummyProfiles = [
  {
    id: "profile-1",
    user: {
      id: "user-1",
      first_name: "Ahmed",
      last_name: "Hassan",
      email: "ahmed@example.com",
      headline: "Senior Full-Stack Developer | React & Node.js Expert",
      location: "Lahore, Pakistan",
      current_role: "Senior Software Engineer",
      current_company: "TechCorp Pakistan",
      experience_level: "senior",
      profile_completed: true,
      is_tutor: true,
      tutor_approved: true,
    },
    summary: "Passionate software engineer with 6+ years of experience building scalable web applications. I love mentoring junior developers and contributing to open source projects.",
    linkedin_url: "https://linkedin.com/in/ahmedhassan",
    github_url: "https://github.com/ahmedhassan",
    portfolio_url: "https://ahmedhassan.dev",
    career_goals: "Lead a team of talented engineers and build products that impact millions of users.",
    interests: ["Web Development", "System Design", "Open Source", "Mentoring"],
    available_for_tutoring: true,
    available_for_mentoring: true,
    is_public: true,
    completeness_score: 95,
    work_experiences: [
      {
        id: 1,
        title: "Senior Software Engineer",
        company: "TechCorp Pakistan",
        location: "Lahore",
        start_date: "2023-01-01",
        end_date: null,
        is_current: true,
        description: "Leading a team of 5 developers building enterprise SaaS products.",
        skills_used: ["React", "Node.js", "PostgreSQL", "AWS"],
      },
      {
        id: 2,
        title: "Software Engineer",
        company: "StartupXYZ",
        location: "Karachi",
        start_date: "2020-06-01",
        end_date: "2022-12-31",
        is_current: false,
        description: "Built and maintained multiple client-facing applications.",
        skills_used: ["React", "Express", "MongoDB"],
      },
    ],
    education: [
      {
        id: 1,
        degree: "BS Computer Science",
        institution: "LUMS",
        field_of_study: "Computer Science",
        start_year: 2016,
        end_year: 2020,
        grade: "3.8 GPA",
      },
    ],
    skills: [
      { name: "React", proficiency: "expert", years: 5 },
      { name: "Node.js", proficiency: "expert", years: 5 },
      { name: "TypeScript", proficiency: "advanced", years: 3 },
      { name: "PostgreSQL", proficiency: "advanced", years: 4 },
      { name: "AWS", proficiency: "intermediate", years: 2 },
    ],
    projects: [
      {
        id: 1,
        name: "E-Commerce Platform",
        description: "Built a full-stack e-commerce platform handling 10K+ daily orders",
        technologies: ["React", "Node.js", "PostgreSQL"],
        github_url: "https://github.com/ahmedhassan/ecommerce",
      },
    ],
    certifications: [
      {
        id: 1,
        name: "AWS Solutions Architect",
        issuer: "Amazon Web Services",
        issue_date: "2025-06-15",
      },
    ],
  },
  {
    id: "profile-2",
    user: {
      id: "user-2",
      first_name: "Sara",
      last_name: "Khan",
      email: "sara@example.com",
      headline: "Data Scientist | ML Engineer | Python Expert",
      location: "Islamabad, Pakistan",
      current_role: "Data Scientist",
      current_company: "DataTech Solutions",
      experience_level: "mid",
      profile_completed: true,
      is_tutor: false,
      tutor_approved: false,
    },
    summary: "Data scientist with expertise in machine learning and deep learning. Passionate about using AI to solve real-world problems.",
    linkedin_url: "https://linkedin.com/in/sarakhan",
    github_url: "https://github.com/sarakhan",
    portfolio_url: "",
    career_goals: "Become a leading AI researcher and build impactful ML products.",
    interests: ["Machine Learning", "Deep Learning", "NLP", "Computer Vision"],
    available_for_tutoring: false,
    available_for_mentoring: true,
    is_public: true,
    completeness_score: 85,
    work_experiences: [
      {
        id: 1,
        title: "Data Scientist",
        company: "DataTech Solutions",
        location: "Islamabad",
        start_date: "2023-03-01",
        end_date: null,
        is_current: true,
        description: "Building ML models for predictive analytics and recommendation systems.",
        skills_used: ["Python", "TensorFlow", "scikit-learn", "SQL"],
      },
    ],
    education: [
      {
        id: 1,
        degree: "MS Data Science",
        institution: "NUST",
        field_of_study: "Data Science",
        start_year: 2021,
        end_year: 2023,
        grade: "3.9 GPA",
      },
    ],
    skills: [
      { name: "Python", proficiency: "expert", years: 4 },
      { name: "TensorFlow", proficiency: "advanced", years: 3 },
      { name: "Machine Learning", proficiency: "advanced", years: 3 },
      { name: "SQL", proficiency: "advanced", years: 4 },
    ],
    projects: [],
    certifications: [],
  },
  {
    id: "profile-3",
    user: {
      id: "user-3",
      first_name: "Ali",
      last_name: "Raza",
      email: "ali@example.com",
      headline: "UI/UX Designer | Product Designer",
      location: "Karachi, Pakistan",
      current_role: "Senior Product Designer",
      current_company: "DesignStudio",
      experience_level: "senior",
      profile_completed: true,
      is_tutor: true,
      tutor_approved: true,
    },
    summary: "Creative product designer with 7 years of experience crafting beautiful and intuitive user experiences.",
    linkedin_url: "https://linkedin.com/in/aliraza",
    github_url: "",
    portfolio_url: "https://aliraza.design",
    career_goals: "Lead design at a major tech company and mentor the next generation of designers.",
    interests: ["UI Design", "UX Research", "Design Systems", "Accessibility"],
    available_for_tutoring: true,
    available_for_mentoring: true,
    is_public: true,
    completeness_score: 90,
    work_experiences: [
      {
        id: 1,
        title: "Senior Product Designer",
        company: "DesignStudio",
        location: "Karachi",
        start_date: "2022-01-01",
        end_date: null,
        is_current: true,
        description: "Leading design for multiple B2B SaaS products.",
        skills_used: ["Figma", "User Research", "Prototyping"],
      },
    ],
    education: [
      {
        id: 1,
        degree: "BFA Graphic Design",
        institution: "NCA",
        field_of_study: "Graphic Design",
        start_year: 2014,
        end_year: 2018,
        grade: "First Class",
      },
    ],
    skills: [
      { name: "Figma", proficiency: "expert", years: 5 },
      { name: "UI Design", proficiency: "expert", years: 7 },
      { name: "UX Research", proficiency: "advanced", years: 5 },
      { name: "Prototyping", proficiency: "expert", years: 6 },
    ],
    projects: [],
    certifications: [],
  },
];

export const platformStats = {
  total_users: 52000,
  total_tutors: 180,
  total_companies: 75,
  total_courses: 45,
  total_enrollments: 15000,
};
