import type {
  User,
  Course,
  Module,
  VerifiedProject,
  Article,
  JobPosting,
  Scholarship,
  CareerPathStep,
  Notification,
} from "@/types";

/**
 * Mock Data for UI Development
 * All data fetching will use these mocks until backend integration.
 */

export const mockUsers: User[] = [
  {
    id: "1",
    email: "learner@skillversity.com",
    name: "Ahmed Khan",
    role: "learner",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed",
    bio: "Aspiring full-stack developer passionate about building impactful solutions.",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "2",
    email: "tutor@skillversity.com",
    name: "Fatima Ali",
    role: "tutor",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima",
    bio: "Senior Software Engineer with 10+ years of experience in web development.",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2024-03-18"),
  },
  {
    id: "3",
    email: "company@skillversity.com",
    name: "TechCorp HR",
    role: "company",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=TechCorp",
    bio: "Leading software house in Pakistan, hiring top talent.",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-03-21"),
  },
  {
    id: "4",
    email: "sponsor@skillversity.com",
    name: "Pakistan Tech Foundation",
    role: "sponsor",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Foundation",
    bio: "NGO supporting tech education for underprivileged youth.",
    createdAt: new Date("2023-12-01"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "5",
    email: "general@skillversity.com",
    name: "Sara Ahmed",
    role: "general",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sara",
    bio: "Exploring career options in tech, seeking guidance.",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-21"),
  },
];

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Full-Stack Web Development with Next.js",
    description: "Master modern web development with Next.js, React, and TypeScript.",
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800",
    difficulty: "intermediate",
    tutorId: "2",
    modules: [],
    enrolledCount: 1247,
    rating: 4.8,
    duration: 2400,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "2",
    title: "Python for Data Science",
    description: "Learn Python programming and data analysis with pandas, numpy, and matplotlib.",
    thumbnail: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800",
    difficulty: "beginner",
    tutorId: "2",
    modules: [],
    enrolledCount: 2341,
    rating: 4.9,
    duration: 1800,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-03-18"),
  },
  {
    id: "3",
    title: "Advanced React Patterns",
    description: "Deep dive into advanced React patterns, hooks, and performance optimization.",
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800",
    difficulty: "advanced",
    tutorId: "2",
    modules: [],
    enrolledCount: 892,
    rating: 4.7,
    duration: 3000,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-03-20"),
  },
];

export const mockModules: Module[] = [
  {
    id: "1",
    courseId: "1",
    title: "Introduction to Next.js",
    description: "Learn the fundamentals of Next.js and its App Router.",
    order: 1,
    videoUrl: "https://example.com/video1.mp4",
    documentation: "# Introduction\n\nNext.js is a React framework...",
    duration: 45,
    isCompleted: false,
  },
];

export const mockProjects: VerifiedProject[] = [
  {
    id: "1",
    userId: "1",
    title: "E-Commerce Platform",
    description: "A full-featured e-commerce platform built with Next.js and Stripe.",
    technologies: ["Next.js", "TypeScript", "Stripe", "PostgreSQL"],
    repositoryUrl: "https://github.com/example/ecommerce",
    liveUrl: "https://example-ecommerce.vercel.app",
    status: "verified",
    verifiedBy: "2",
    verifiedAt: new Date("2024-03-10"),
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "2",
    userId: "1",
    title: "Task Management System",
    description: "A collaborative task management application with real-time updates.",
    technologies: ["React", "Node.js", "Socket.io", "MongoDB"],
    repositoryUrl: "https://github.com/example/taskmanager",
    liveUrl: "https://example-tasks.vercel.app",
    status: "verified",
    verifiedBy: "2",
    verifiedAt: new Date("2024-03-15"),
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "3",
    userId: "1",
    title: "Weather Dashboard",
    description: "Real-time weather dashboard with data visualization and forecasting.",
    technologies: ["Vue.js", "Python", "FastAPI", "Chart.js"],
    repositoryUrl: "https://github.com/example/weather",
    liveUrl: "https://example-weather.vercel.app",
    status: "pending",
    verifiedBy: undefined,
    verifiedAt: undefined,
    createdAt: new Date("2024-03-18"),
  },
];

export const mockArticles: Article[] = [
  {
    id: "1",
    title: "Understanding Server Components in Next.js",
    content: "# Server Components\n\nServer Components are a revolutionary feature in Next.js that allows you to render components on the server. This approach provides better performance and SEO benefits.\n\n## Benefits\n\n- Reduced JavaScript bundle size\n- Better initial page load\n- Improved SEO\n- Direct database access",
    authorId: "1",
    coAuthors: [],
    tags: ["Next.js", "React", "Server Components"],
    publishedAt: new Date("2024-03-15"),
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "2",
    title: "Building Scalable APIs with FastAPI",
    content: "# FastAPI Guide\n\nFastAPI is a modern, fast web framework for building APIs with Python. It's built on top of Starlette and Pydantic.\n\n## Key Features\n\n- Automatic API documentation\n- Type hints support\n- High performance\n- Easy to learn",
    authorId: "1",
    coAuthors: [],
    tags: ["Python", "FastAPI", "Backend"],
    publishedAt: new Date("2024-03-18"),
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-18"),
  },
  {
    id: "3",
    title: "TypeScript Best Practices for 2024",
    content: "# TypeScript Best Practices\n\nTypeScript has become the standard for building large-scale JavaScript applications. Here are the best practices you should follow.\n\n## Type Safety\n\n- Use strict mode\n- Avoid 'any' type\n- Leverage union types\n- Use generics effectively",
    authorId: "2",
    coAuthors: [],
    tags: ["TypeScript", "JavaScript", "Best Practices"],
    publishedAt: new Date("2024-03-20"),
    createdAt: new Date("2024-03-18"),
    updatedAt: new Date("2024-03-20"),
  },
];

export const mockJobs: JobPosting[] = [
  {
    id: "1",
    companyId: "3",
    title: "Junior Full-Stack Developer",
    description: "We are looking for a passionate junior developer to join our growing team. You'll work on exciting projects using modern technologies.",
    requirements: ["Next.js", "TypeScript", "PostgreSQL"],
    location: "Karachi, Pakistan",
    type: "full-time",
    salary: {
      min: 80000,
      max: 120000,
      currency: "PKR",
    },
    postedAt: new Date("2024-03-18"),
    expiresAt: new Date("2024-04-18"),
  },
  {
    id: "2",
    companyId: "3",
    title: "Senior React Developer",
    description: "Seeking an experienced React developer to lead our frontend team and mentor junior developers.",
    requirements: ["React", "TypeScript", "Redux", "5+ years experience"],
    location: "Lahore, Pakistan",
    type: "full-time",
    salary: {
      min: 200000,
      max: 300000,
      currency: "PKR",
    },
    postedAt: new Date("2024-03-20"),
    expiresAt: new Date("2024-04-20"),
  },
  {
    id: "3",
    companyId: "3",
    title: "Python Backend Intern",
    description: "Great opportunity for students to gain real-world experience in backend development.",
    requirements: ["Python", "FastAPI", "SQL"],
    location: "Remote",
    type: "internship",
    salary: {
      min: 30000,
      max: 50000,
      currency: "PKR",
    },
    postedAt: new Date("2024-03-19"),
    expiresAt: new Date("2024-04-19"),
  },
];

export const mockScholarships: Scholarship[] = [
  {
    id: "1",
    partnerId: "4",
    title: "Tech for Pakistan Scholarship",
    description: "Supporting underprivileged students in tech education.",
    amount: 50000,
    currency: "PKR",
    eligibilityCriteria: ["Pakistani citizen", "Age 18-25", "Financial need"],
    applicationDeadline: new Date("2024-05-01"),
    createdAt: new Date("2024-03-01"),
  },
];

export const mockCareerPath: CareerPathStep[] = [
  {
    id: "1",
    title: "Complete Profile",
    description: "Set up your professional profile",
    isCompleted: true,
    order: 1,
  },
  {
    id: "2",
    title: "Enroll in First Course",
    description: "Start your learning journey",
    isCompleted: true,
    order: 2,
  },
  {
    id: "3",
    title: "Complete First Project",
    description: "Build and submit your first project",
    isCompleted: false,
    order: 3,
  },
  {
    id: "4",
    title: "Get Project Verified",
    description: "Have your project verified by a tutor",
    isCompleted: false,
    order: 4,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "1",
    userId: "1",
    title: "Project Verified",
    message: "Your E-Commerce Platform project has been verified!",
    type: "success",
    isRead: false,
    createdAt: new Date("2024-03-20T10:30:00"),
  },
  {
    id: "2",
    userId: "1",
    title: "New Course Available",
    message: "Check out the new Advanced React Patterns course!",
    type: "info",
    isRead: false,
    createdAt: new Date("2024-03-21T09:15:00"),
  },
  {
    id: "3",
    userId: "1",
    title: "Job Match Found",
    message: "A new job posting matches your skills: Junior Full-Stack Developer",
    type: "info",
    isRead: true,
    createdAt: new Date("2024-03-19T14:20:00"),
  },
];
